### ISSUE TITLE
Unable to make Hide-Ads-In-Gmail function (Custom CSS)

### ISSUE THREAD

**Issue by live4truths** [Thomas101/wmail-user-scripts#4] opened 2017-01-08 17:28 UTC
Greetings,

Thank you for your reply in the other issue tracker. I have attempted to deploy the hide-ads-in-gmail custom CSS in WMail, unfortunately they are not hiding the ads under the different tabular areas.

When inspecting the elements, they are referencing classes that the script does not. Under the "Promotions" tab for example the table class is "F cf" and item class being "aKA D6NH0b zE".

Please let me know if I am missing something and would  be happy to help.

Thank you!

**Comment by axllent** [comment] 2017-01-09 00:49
Hi,

I got your email too, however it's probably best to respond here ;-)

To be honest I'm not sure as it appears (from what I can debug) to be something regional-based, or possibly even language based. Either way, I cannot see those adverts (I've tried with VPN etc but no luck). The `table class="F cf ..."` appears to be the message overview/list, so don't hide that!

Maybe just try add the following to see if it helps:
```
.aKA.D6NH0b {
  display: none!important;
}
```
Please let me know if that helps (and doesn't unintentionally hide all anything else)?

Cheers,
Ralph

**Comment by live4truths** [comment] 2017-01-09 02:36
Hi Ralph!

I wholeheartedly appreciate your response. Adding your code removed the ads on both the Promotions and Social Tabs, however there is a bar still showing on both of those. Using the inspect it goes to a

`<div class="a2q">...</div> == $0`

Any suggestions on how to remove the bar? This is a major improvement sofar!

Thank you!

**Comment by axllent** [comment] 2017-01-09 06:22
Glad to hear you're getting somewhere. At this point I'd ave to say "you're on your own" as I cannot reproduce those ads, so I don't know the DOM structure in the parent elements of those hidden elements. By the sounds of it you seem to understand the concept though, "inspecting" the elements. Generally you'll see the "affected" areas by hovering over the DOM elements in the developer tools and seeing what gets highlighted on the main screen. Try get as "high up" as you can and then try add a CSS class like the one above to include that element. Often those elements have multiple classes (including a single randomly generated class name), so you sometimes have to play a bit and see what works.

Please post back with your results, and if successful then I'll update my ad-blocking css and send a pull request to @Thomas101

**Comment by live4truths** [comment] 2017-01-09 07:05
Got it 100%.

Utilizing this, was able to remove all signs of the ad bars, and any traces with no UI weirdness.

```
.aKA.D6NH0b {
  display: none!important;
}

.a2q {
  display: none!important;
}

.aK1 {
  display: none!important;
}

```
Going to assume that over time these div classes will change, I can keep them up to date as long as I use the program.

.aKA.D6NH0b was generated for the ad data itself
.a2q was generated for the extra bar on the "Promotions" tab
.aK1 was generated for the extra bar on the "Social" tab

Thank you for the assist!

**Comment by axllent** [comment] 2017-01-09 07:14
I'm going to assume (from experience) that the `D6NH0b` in `aKA.D6NH0b` is temporary.

Can you please try it without that and see if it still works? ie:
```
.aKA {
  display: none!important;
}

.a2q {
  display: none!important;
}

.aK1 {
  display: none!important;
}
```

**Comment by live4truths** [comment] 2017-01-09 07:29
Removing the `D6NH0b` had no affect. Looks good still at this point.

**Comment by axllent** [comment] 2017-01-09 07:32
Thanks for the feedback! I added your code on this end and it seems to be fine here too.

Awesome!

**Comment by live4truths** [comment] 2017-01-09 07:33
Great! Thanks for assisting in the debug, if you're not seeing the ads, I am assuming its either an NA or United States thing. I will keep you apprised if there are any changes moving forward. (At least until @Thomas101 can get Chrome Extensions working :)

Thank you again!

**Comment by axllent** [comment] 2017-01-09 07:46
No problem, glad to help, and appreciate the feedback too! You can close this issue if you like (unless you prefer to wait for PR #5 to be merged).

**Closed as completed** 2017-01-09 08:14 UTC

**Comment by Thomas101** [comment] 2017-01-10 17:45
Thanks! I've merged this now :)
